### ISSUE TITLE
Regression: Regexp is no longer considered extendable

### ISSUE THREAD

**Issue by realityking** [jonschlinkert/is-extendable#2]
While trying to update `extend-shallow` to use version 1.0.1 I discovered there's a regression.

To reproduce:

```js
var isExtendable = require('is-extendable');

var regex = /foo/;
console.log(isExtendable(regex));
```

**Comment by jonschlinkert** [comment]
See the [release history](https://github.com/jonschlinkert/is-extendable#release-history). 

This is a good example of why bumping packages should only be done to fix a problem. There is no other good reason to bump IMHO, as we're only creating the potential for bugs and edge cases to crop up.

**Comment by realityking** [comment]
Didn't see the changelog. Thanks.

**Comment by jonschlinkert** [comment]
another good reason would be a quantifiable, demonstrable improvement in performance. Again, just my humble opinion, and I'm willing to merge bumps if they are important to users, such as yourself.

**Comment by jonschlinkert** [comment]
fwiw, we have an auto-generated "report card" that shows us how many contributions we've had on our projects, so we make it a goal to increase that number. From that standpoint getting more PRs is awesome. 

Over the long term, though, I believe we will always get more contributors if we're good stewards of our projects, so my goal was just to share information that might help you decide how you'd like to proceed, by telling you a potential side effect of doing PRs to bump deps. sorry if it came off as preachy
